### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by TimenoLong** [hustvl/GaussianDreamer#47]
Complete error as follows:
:Traceback (most recent call last):
  File "/home/wyx/yangchenlong/GaussianDreamer-main/launch.py", line 240, in <module>
    main(args, extras)
  File "/home/wyx/yangchenlong/GaussianDreamer-main/launch.py", line 183, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interr
    return trainer_fn(*args, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 268, in _optim
    call._call_lightning_module_hook(
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 167, in _call_lightning_module
    output = fn(*args, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1306, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 153, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 238, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/amp.py", line 78, in optimizer_step
    closure_result = closure()
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 144, in __call
    self._result = self.closure(*args, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 129, in closur
    step_output = self._step_fn()
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 317, in _train
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/home/wyx/yangchenlong/GaussianDreamer-main/threestudio/systems/GaussianDreamer.py", line 291, in training_step
    out = self(batch)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wyx/anaconda3/envs/splatterimage/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wyx/yangchenlong/GaussianDreamer-main/threestudio/systems/GaussianDreamer.py", line 240, in forward
    render_pkg = render(viewpoint_cam, self.gaussian, self.pipe, renderbackground)
  File "/home/wyx/yangchenlong/GaussianDreamer-main/gaussiansplatting/gaussian_renderer/__init__.py", line 86, in render
    rendered_image, radii ,depth= rasterizer(
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Eminemowen** [comment]
Hello, have you solved this problem?
